server:
  port: 8082
spring:
  application:
    name: "catalog"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

        
        
        
        