spring:
  application: 
    name: eurekaserver 
  profiles:
    active: dev 
  rabbitmq:
    host: localhost
    port: 5672 
    username: guest
    password: guest
  config:
    import: "optional:configserver:http://localhost:8071/"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"