server:
  port: 8081
spring:
  application:
    name: "booking"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
