server:
  port: 8081
spring:
  application:
    name: "booking"
  profiles:
    active: "dev"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.losolved.booking: DEBUG
  file:
    name: logs/spring-boot-application.log
  pattern:
    console: "%d{dd/MM/yyyy HH:mm:ss} - %msg%n"
    file: "%d{dd/MM/yyyy HH:mm:ss} - %msg%n"
